-- CreateTable
CREATE TABLE "PaymentMethod" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "paymentMethodId" STRING NOT NULL,
    "lastFour" STRING NOT NULL,
    "brand" STRING NOT NULL,
    "userId" INT4 NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PaymentMethod_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "PaymentMethod_userId_paymentMethodId_key" ON "PaymentMethod"("userId", "paymentMethodId");

-- AddForeignKey
ALTER TABLE "PaymentMethod" ADD CONSTRAINT "PaymentMethod_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
