/*
  Warnings:

  - Added the required column `updatedAt` to the `UserMailService` table without a default value. This is not possible if the table is not empty.
  - Added the required column `userId` to the `UserMailService` table without a default value. This is not possible if the table is not empty.

*/
-- AlterTable
ALTER TABLE "UserMailService" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "UserMailService" ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL;
ALTER TABLE "UserMailService" ADD COLUMN     "userId" INT4 NOT NULL;
ALTER TABLE "UserMailService" ALTER COLUMN "document_url" DROP NOT NULL;

-- CreateTable
CREATE TABLE "User" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "fullName" STRING NOT NULL,
    "email" STRING NOT NULL,
    "password" STRING NOT NULL,
    "subscriptionStart" TIMESTAMP(3) NOT NULL,
    "subscriptionActive" BOOL NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Account" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "provider" STRING NOT NULL,
    "providerAccountId" STRING NOT NULL,
    "userId" INT4 NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Account_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- AddForeignKey
ALTER TABLE "Account" ADD CONSTRAINT "Account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserMailService" ADD CONSTRAINT "UserMailService_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
