/*
  Warnings:

  - You are about to alter the column `id` on the `UserMailService` table. The data in that column will be cast from `BigInt` to `Int`. This cast may fail. Please make sure the data in the column can be cast.

*/
-- RedefineTables
CREATE TABLE "_prisma_new_UserMailService" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "document_url" STRING NOT NULL,
    "contact_toReceiverName" STRING NOT NULL,
    "contact_ToReceiverAddress" STRING NOT NULL,
    "contact_ToReceiverCity" STRING NOT NULL,
    "contact_ToReceiverState" STRING NOT NULL,
    "contact_ToReceiverZipCode" STRING NOT NULL,
    "contact_FromSenderName" STRING NOT NULL,
    "contact_FromSenderAddress" STRING NOT NULL,
    "Contact_FromSenderCity" STRING NOT NULL,
    "contact_FromSenderState" STRING NOT NULL,
    "contact_FromSenderZipCode" STRING NOT NULL,
    "contact_sendDate" TIMESTAMP(3) NOT NULL,
    "Contact_TypeofMail" STRING NOT NULL,
    "contact_paperSize" STRING NOT NULL,
    "pdfLink" STRING,

    CONSTRAINT "UserMailService_pkey" PRIMARY KEY ("id")
);
INSERT INTO "_prisma_new_UserMailService" ("Contact_FromSenderCity","Contact_TypeofMail","contact_FromSenderAddress","contact_FromSenderName","contact_FromSenderState","contact_FromSenderZipCode","contact_ToReceiverAddress","contact_ToReceiverCity","contact_ToReceiverState","contact_ToReceiverZipCode","contact_paperSize","contact_sendDate","contact_toReceiverName","document_url","id","pdfLink") SELECT "Contact_FromSenderCity","Contact_TypeofMail","contact_FromSenderAddress","contact_FromSenderName","contact_FromSenderState","contact_FromSenderZipCode","contact_ToReceiverAddress","contact_ToReceiverCity","contact_ToReceiverState","contact_ToReceiverZipCode","contact_paperSize","contact_sendDate","contact_toReceiverName","document_url","id","pdfLink" FROM "UserMailService";
DROP TABLE "UserMailService" CASCADE;
ALTER TABLE "_prisma_new_UserMailService" RENAME TO "UserMailService";
